FROM node:21 AS frontend-builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

COPY .env.docker .env.local

RUN npm run build

FROM nginx:alpine

COPY --from=frontend-builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
